apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  type: NodePort 
  selector:
   app: go-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080